
name: nightly-canary

on:
  schedule:
    - cron: "17 3 * * *"   # daily at 03:17 UTC
  workflow_dispatch:

jobs:
  canary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Upgrade pip
        run: python -m pip install -U pip

      - name: Install latest of everything (canary)
        run: |
          pip install -U -e .
          pip install -U ".[dev]"
      - name: Run tests
        run: pytest -q
